import meta from "./image-meta.json";

/** Descriptive alt text for every photo in /public/images (slug → alt). */
export const alts: Record<string, string> = {
  "golden-grass": "Tall grass glowing in late golden-hour light",
  "lawn-chairs-golden": "Two lawn chairs on a lush green lawn in warm evening light",
  "garden-sunlit-trees": "Sunlit meadow garden framed by autumn trees",
  "grasses-backlit": "Ornamental grasses backlit by low sun in a planted bed",
  "dried-flowers-backlit": "Dried flower heads backlit by warm sunlight",
  "backyard-sunlit": "Sunlight filtering through tree canopy over a backyard",
  "stepping-stones-lawn": "Natural stone stepping path set into a green lawn",
  "sprinkler-lawn": "Pop-up sprinkler watering a green lawn",
  "sprinklers-golden": "Sprinklers watering turf at golden hour",
  "sprinkler-bed": "Garden sprinkler misting a bed beside a tree",
  "estate-lawn-hedges": "Long manicured lawn with mowing stripes between clipped hedges",
  "striped-lawn": "Freshly mown lawn with crisp alternating stripes",
  "lawn-stripes-shadow": "Mowing stripes and long evening shadows across a lawn",
  "crew-mowing": "Lawn care crew member mowing a residential lawn",
  "mower-closeup": "Close view of a lawn mower cutting grass",
  "front-yard-landscaped": "Front yard with fresh lawn, edged beds and shrubs",
  "mowing-backyard": "Push mower on a neatly cut backyard lawn",
  "string-trimmer": "Crew member trimming lawn edges with a string trimmer",
  "riding-mower": "Crew member on a ride-on mower across a large lawn",
  "estate-driveway": "Large home with winding driveway and manicured lawn",
  "brick-home-lawn": "Brick home with a lush, evenly mown front lawn",
  "brick-home-lawn-2": "Two-story home with a green front lawn and trimmed shrubs",
  "brick-home-trees": "Brick house framed by mature trees and a healthy lawn",
  "circular-patio": "Circular paved patio edged by a low stone wall and shrubs",
  "patio-firepit-house": "Stone patio with dark wood chairs and a fire pit beside the house",
  "curved-stone-steps": "Curved stone steps leading down to a paved seating area",
  "stone-patio-pool": "Small pool with white umbrella on a stone patio",
  "curved-seating-patio": "Curved stone seating area with steps and greenery",
  "firepit-dusk": "Fire pit burning at dusk on a backyard lawn",
  "adirondack-firepit": "Adirondack chairs around a fire pit in a flowering backyard",
  "firepit-evening": "Adirondack chairs around a lit fire pit in the evening",
  "outdoor-fireplace": "Outdoor stone fireplace with burning logs on a covered deck",
  "outdoor-kitchen-bar": "Modern outdoor kitchen with a bar and seating",
  "outdoor-kitchen-island": "Outdoor kitchen island with bar stools under a covered patio",
  "outdoor-kitchen-pool": "Covered outdoor kitchen opening onto a pool deck",
  "pool-kitchen-patio": "Pool patio with an outdoor kitchen and lounge seating",
  "covered-patio": "Covered patio with a grill and dining table",
  pergola: "Wooden bench beneath a timber pergola",
  "lit-shrubs": "Shrubs softly uplit by landscape lights at night",
  "lit-hedge-white": "Green bushes glowing under white landscape lights at night",
  "recessed-path-lights": "Recessed ground lights along a brick walkway at night",
  "lit-garden-trees": "Garden bench and trees lit at night",
  "garden-night-glow": "Warm garden lights glowing among trees and mulch at night",
  "grasses-night": "Potted grasses and flowers under soft dusk lighting",
  "house-dusk-lawn": "White house with glowing windows and a stone path at dusk",
  "house-dusk-hillside": "House among trees with warm porch lights at dusk",
  "garden-path-perennials": "Garden path lined with flowering perennials",
  coneflowers: "Pink coneflowers in full bloom",
  "orange-blooms": "Orange flowers blooming in a sunny bed",
  salvia: "Purple salvia spikes in a perennial border",
  "grasses-coneflower": "Ornamental grasses mixed with coneflowers",
  "purple-border": "Purple flowering border beside a garden path",
  echinacea: "Echinacea blooms in a naturalistic planting",
  "russian-sage": "Drift of lavender Russian sage",
  "fountain-grass": "Fountain grass moving in the breeze",
  "golden-grasses": "Golden ornamental grasses in autumn light",
  "grasses-meadow": "Meadow of feathery ornamental grasses",
  "xeriscape-yucca": "Xeriscape garden with yucca, rocks and gravel",
  "xeriscape-cactus": "Water-wise garden with barrel cactus and gravel",
  "red-yucca": "Red yucca with arching red-tinged leaves",
  agave: "Sculptural agave rosette",
  "gardener-bed": "Gardener tending a raised planting bed",
  "topiary-crew": "Gardener shaping topiary on a lawn",
  "landscaper-tool": "Landscaper working a bed with a hand tool",
  wheelbarrow: "Crew member pushing a wheelbarrow across a lawn",
  "gardener-path": "Gardener working beside a curved front path",
  "planting-golden": "Landscaper planting in fresh soil in golden light",
  "hands-planting": "Hands setting a young plant into soil",
  "hands-grass": "Hands checking the health of lawn grass",
  "hands-soil": "Hands planting seedlings in a garden bed",
  "hedge-trimmer": "Crew member shaping a hedge with a power trimmer",
  "hedge-trim-top": "Hedge trimmer leveling the top of a hedge",
  mulch: "Fresh hardwood mulch spread in a bed",
  "mulch-dark": "Dark shredded mulch texture",
  "planting-shrub": "Gardener planting a shrub",
  "gloves-planting": "Gloved hands planting flowers in a bed",
  "spring-redbud": "Pink spring blossoms over a lawn and park bench",
  "spring-garden-sun": "Spring garden bathed in morning sun",
  "spring-blossom": "Pale pink spring blossoms on a branch",
  "summer-grass": "Close view of healthy summer lawn grass",
  "summer-yard": "Shady summer yard with lawn and white chairs",
  "summer-lawn-trees": "Summer lawn beneath tall shade trees",
  "fall-lawn-leaves": "Autumn leaves scattered across a green lawn",
  "fall-red-tree": "Red and orange fall tree over a picket fence",
  "fall-trees-house": "Golden fall trees in front of a stone building",
  "fall-path": "Garden path lined with autumn color",
  "fall-leaves-woods": "Fallen leaves covering the ground under trees",
  "fall-raking": "Raking fallen leaves into a pile",
  "winter-frost-grass": "Frost on blades of grass on a winter morning",
  "winter-frost-seed": "Frost-covered seed heads in winter light",
  "winter-frost-ground": "Frosted leaves on the ground",
  "winter-frost-leaf": "Frost crystals edging green leaves",
  "arborist-climb": "Arborist climbing a tree with ropes",
  arborist: "Arborist pruning a tree limb",
  "arborist-saw": "Arborist making a pruning cut",
  "pruning-shears": "Hand pruners shaping a shrub",
  "oak-sunset": "Lone oak tree in a field at sunset",
  "oak-bench": "Bench beneath a spreading oak in golden light",
  "pool-dusk": "Backyard pool and patio lit at dusk",
  "pool-texas": "Freeform pool with stone decking and palms",
  "pool-patio-dusk": "Pool and lounge patio at dusk",
  "pool-sunset": "Backyard pool at sunset",
  "pool-garden": "Pool surrounded by layered garden planting",
  "bluebonnets-house": "Texas bluebonnets in front of a stone house",
  bluebonnets: "Close view of Texas bluebonnets",
  "bluebonnets-sunset": "Bluebonnet field at sunset",
  fern: "Fern frond",
  fiddlehead: "Fern fiddlehead unfurling",
  "fiddlehead-2": "Curled fern fiddleheads",
  "fiddlehead-3": "Unfurling fern frond",
  "garden-path-stone": "Stone path winding through a garden",
  "stone-steps-green": "Stone steps through lush green planting",
  "flagstone-path": "Flagstone path through a garden",
  "stone-steps-garden": "Stone steps in a shady garden",
  "rock-garden-steps": "Natural stone steps through a rock garden",
  "stone-wall": "Stone wall with arches and climbing plants",
  "dry-stone-wall": "Dry-stacked fieldstone wall",
  "retaining-wall-garden": "Planted stone retaining wall",
  "stone-wall-planting": "Stone wall with planting spilling over the top",
  "drip-irrigation": "Drip irrigation line watering young plants",
  "drip-line": "Drip line running along a planted bed",
  "before-empty-yard": "Before: plain fenced backyard with only lawn",
  "before-dead-lawn": "Before: dry, patchy brown lawn",
  "before-weedy-lot": "Before: weedy, sandy front yard",
  "before-bare-yard": "Before: bare backyard with an old fence",
  "install-excavator": "Compact excavator preparing a yard for installation",
  "night-reveal": "Two-story home at dusk with lit lamp post, glowing windows and a landscaped driveway island",
  "craftsman-dusk": "Craftsman home at dusk with warm porch lights and a brick walkway",
  "craftsman-dusk-2": "Craftsman house at dusk framed by a red Japanese maple",
  "hero-poster": "Golden sunlight through oak trees over a green lawn",
  "sprinkler-poster": "Sprinklers watering a field at sunset",
};

/** Intrinsic [width, height] of every photo (generated by scripts/optimize-images.mjs). */
export const imageMeta = meta as unknown as Record<string, [number, number]>;

export const imgSrc = (slug: string) => `/images/${slug}.jpg`;
export const alt = (slug: string) => alts[slug] ?? "";
